# Generated by Django 5.2.8 on 2026-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_post_id', models.IntegerField(db_index=True)),
                ('found_post_id', models.IntegerField(db_index=True)),
                ('combined_score', models.FloatField()),
                ('face_similarity', models.FloatField()),
                ('time_score', models.FloatField()),
                ('location_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Face Match',
                'verbose_name_plural': 'Face Matches',
                'unique_together': {('missing_post_id', 'found_post_id')},
            },
        ),
    ]
