# Generated by Django 5.2.14 on 2026-05-26 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNAMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_post_id', models.IntegerField(db_index=True)),
                ('found_post_id', models.IntegerField(db_index=True)),
                ('match_type', models.CharField(choices=[('direct', 'Direct (Identical Person)'), ('kinship_parent_child', 'Parent-Child Relation'), ('kinship_sibling', 'Sibling Relation')], max_length=30)),
                ('overlap_loci_count', models.IntegerField()),
                ('matching_loci_count', models.IntegerField()),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DNA Match',
                'verbose_name_plural': 'DNA Matches',
                'unique_together': {('missing_post_id', 'found_post_id')},
            },
        ),
        migrations.CreateModel(
            name='DNAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_data', models.JSONField(help_text='STR loci keys mapped to list of alleles.')),
                ('gender', models.CharField(blank=True, help_text='XX, XY, etc.', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dna_profile', to='ai.post')),
            ],
            options={
                'verbose_name': 'DNA Profile',
                'verbose_name_plural': 'DNA Profiles',
            },
        ),
    ]
