import json
import logging
from typing import Dict, Any, Optional
from core.interfaces.llm_client import ILLMClient
from core.interfaces.dna_repository import IDNARepository
from infra.external.llm_client import LLMService
from infra.repositories.django_dna_repository import DjangoDNARepository
from services.face_search_service import FaceSearchService
from services.dna_search_service import DNASearchService

logger = logging.getLogger(__name__)

class AgenticRAGService:
    """
    Agentic RAG Service that orchestrates multimodal search operations
    (Text, Visual, DNA) and uses an LLM to reason over the results.
    """
    
    def __init__(self, llm_client: Optional[ILLMClient] = None, dna_repository: Optional[IDNARepository] = None):
        self.llm = llm_client or LLMService()
        self.face_service = FaceSearchService()
        self.dna_service = DNASearchService()
        self.dna_repo = dna_repository or DjangoDNARepository()
        
    def process_query(self, text_query: str, image_path: Optional[str] = None, dna_data: Optional[Dict] = None) -> str:
        """
        Processes a multimodal query and returns a comprehensive response generated by the LLM.
        """
        logger.info(f"AgenticRAG processing query. Text: {bool(text_query)}, Image: {bool(image_path)}, DNA: {bool(dna_data)}")
        
        context_blocks = []
        
        # 1. Visual Search
        if image_path:
            try:
                face_res = self.face_service.search_face_by_image(image_path, n_results=3, cleanup=True, use_age_progression=True)
                if face_res and face_res.get("status") == "success":
                    matches = face_res.get("search_results", [])
                    if matches:
                        # Extract vital info to save tokens
                        clean_matches = []
                        for m in matches:
                            meta = m.get("metadata") or {}
                            match_dict = {
                                "similarity": m.get("similarity"),
                                "confidence": f"{round((1 - m.get('similarity', 1)) * 100, 1)}%",
                            }
                            
                            status = meta.get("status")
                            if status and status != "unknown": 
                                match_dict["status"] = status
                            else:
                                match_dict["status"] = "غير محدد"
                            
                            image_url = meta.get("original_image")
                            if image_url and image_url != "unknown": 
                                # Format relative local paths to Django media/static paths
                                if "temp_uploads/" in image_url:
                                    image_url = "/media/" + image_url.split("temp_uploads/")[-1]
                                elif "images_vdb/" in image_url:
                                    image_url = "/static/" + image_url.split("images_vdb/")[-1]
                                elif not image_url.startswith("http") and not image_url.startswith("/"):
                                    # Fallback for other relative paths
                                    image_url = "/" + image_url
                                match_dict["imageUrl"] = image_url
                            else:
                                match_dict["imageUrl"] = "MISSING"
                                
                            post_id = meta.get("postId")
                            if post_id and post_id != "unknown": 
                                match_dict["postId"] = post_id
                            else:
                                match_dict["postId"] = "غير معروف"
                            
                            clean_matches.append(match_dict)
                        context_blocks.append(f"Visual Search Results:\n{json.dumps(clean_matches, ensure_ascii=False)}")
                    else:
                        context_blocks.append("Visual Search Results: No matching faces found in the database.")
                else:
                    context_blocks.append(f"Visual Search Results: Search failed or no faces detected in the provided image.")
            except Exception as e:
                logger.error(f"Visual Search Error in Agent: {e}")
                context_blocks.append(f"Visual Search Results: Error occurred - {str(e)}")
                
        # 2. DNA Search
        if dna_data:
            try:
                # Fetch all unresolved profiles from DB for comparison
                targets = self.dna_repo.get_unresolved_profiles_for_matching()
                
                # Perform direct and parent-child matching
                direct_matches = self.dna_service.search_profiles(dna_data, targets, search_type="direct", min_overlap=3)
                kinship_matches = self.dna_service.search_profiles(dna_data, targets, search_type="parent_child", min_overlap=3)
                
                dna_results = []
                if direct_matches:
                    for dm in direct_matches[:3]:
                        dna_results.append({
                            "type": "Direct Match (Identical Person)",
                            "score": round(dm.get("score", 0) * 100, 1),
                            "overlap_loci_count": dm.get("overlap_count"),
                            "postId": dm.get("target_id"),
                            "status": dm.get("metadata", {}).get("postType")
                        })
                
                if kinship_matches:
                    for km in kinship_matches[:3]:
                        dna_results.append({
                            "type": "Kinship Match (Parent-Child)",
                            "score": round(km.get("score", 0) * 100, 1),
                            "overlap_loci_count": km.get("overlap_count"),
                            "postId": km.get("target_id"),
                            "status": km.get("metadata", {}).get("postType")
                        })
                        
                if dna_results:
                    context_blocks.append(f"DNA Search Results:\n{json.dumps(dna_results, ensure_ascii=False)}")
                else:
                    context_blocks.append("DNA Search Results: No compatible DNA matches found in the database.")
            except Exception as e:
                logger.error(f"DNA Search Error in Agent: {e}")
                context_blocks.append(f"DNA Search Results: Error occurred - {str(e)}")
        
        # 3. Text/Metadata RAG (If we had a semantic search for text, we'd add it here)
        # For now, we will rely on the text query being used by the LLM to filter the visual/DNA results context.
        
        # Construct the Prompt for the LLM
        system_prompt = (
            "You are an advanced investigative AI RAG Agent for 'Mafqood' platform (a platform to find missing and found people). "
            "Your objective is to analyze the multimodal search results provided from the backend systems (Face Recognition, DNA matching) "
            "and answer the user's query.\n\n"
            "Rules:\n"
            "1. Answer strictly in Arabic. Provide a 'handsome', well-formatted markdown response.\n"
            "2. If matches were found, present them clearly. Highlight 'confidence', 'postId', and 'status'.\n"
            "3. **CRITICAL IMAGE RULE:** If a match has an 'imageUrl' that is NOT 'MISSING', you MUST embed the image in the response using EXACT markdown syntax: `![صورة الاثر](URL_HERE)`. Make sure the image tag is on its own line.\n"
            "4. If 'imageUrl' is 'MISSING', you MUST write `[صورة غير متوفرة في النظام]` and DO NOT attempt to write an image markdown tag.\n"
            "5. If matches exist but lack 'postId' or 'imageUrl', explain that these are old system records or temporary scans without attached profiles.\n"
            "6. Be professional, supportive, and objective. Do not hallucinate data.\n"
        )
        
        user_content = f"User Query: {text_query if text_query else 'I have provided some files for search.'}\n\n"
        
        if context_blocks:
            user_content += "--- CONTEXT FROM DATABASE SEARCHES (SYSTEM EXTRACTED) ---\n"
            for idx, block in enumerate(context_blocks, 1):
                user_content += f"[{idx}] {block}\n\n"
            user_content += "--------------------------------------------------------\n"
            user_content += "Based on these results, please provide a comprehensive summary and advice for the user."
        else:
            user_content += "No search attachments (image/DNA) were provided. The database search was not executed. Please ask the user to provide an image or DNA data."
        
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content}
        ]
        
        logger.info(f"Agent Context Payload: {user_content}")
        
        # Call LLM
        response = self.llm._call_llm_messages(messages, temperature=0.6)
        if not response:
             response = "عذراً، حدث خطأ أثناء الاتصال بالمساعد الذكي. يرجى المحاولة مرة أخرى."
             
        return response
